# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS_Demo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS_Demo
  pod 'Alamofire', '~> 5.2'
  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'SDWebImage'

  target 'iOS_DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOS_DemoUITests' do
    # Pods for testing
  end

end
